### ISSUE TITLE
Why there is no fst, snd?

### ISSUE THREAD

**Issue by nikita-leonov** [robrix/Prelude#47] opened 2016-05-11 17:36 UTC
Thanks for the work so far! It helps a lot. We were writing our own prelude, but it seems redundant when this uframework in place. 

In our implementation we have `fst` & `snd` for tuple unwraps. It known Haskell functions that allows to avoid in place anonymous functions like { $0 } or { $0.0 } etc. We have a code guidelines to prefer functions & functions compositions in our code instead of closures. It would be great to have such functions in Prelude. What do you think? I can provide PR if proposal sounds reasonable.

**Comment by nikita-leonov** [comment] 2016-05-11 17:37
@robrix hm, I just noticed #44. Is it the same proposal? I am not sure that I understand description of it clearly :)

**Comment by robrix** [comment] 2016-05-11 18:36
Yep, this is a duplicate of #44. A PR would be welcomed!

**Closed by robrix** 2016-05-11 18:36 UTC
